Class {
	#name : 'SRActionPragmaBuilder',
	#superclass : 'SRPragmaBuilder',
	#category : 'SimpleRene-Model-Utility',
	#package : 'SimpleRene-Model',
	#tag : 'Utility'
}

{ #category : 'constants' }
SRActionPragmaBuilder class >> simpleReneDescriptionExtensionPragma [ 
	^ #simpleReneActionDescription:
]

{ #category : 'constants' }
SRActionPragmaBuilder class >> simpleReneDescriptionPragma [ 
	^ #simpleReneActionDescription
]
